import type { Person, Decedent } from '../types/models';

export interface Preset {
  label: string;
  description: string;
  decedent: Decedent;
  persons: Person[];
}

export const PRESETS: Preset[] = [
  {
    label: '配偶＋2名子女',
    description: '最常見的繼承情形，配偶與子女均分遺產',
    decedent: {
      id: 'preset_1_decedent',
      name: '王大明',
      deathDate: '2024-06-15',
      estateAmount: 18000000,
    },
    persons: [
      {
        id: 'preset_1_1',
        name: '李小華',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1965-09-12',
        marriageDate: '1990-11-03',
      },
      {
        id: 'preset_1_2',
        name: '王一郎',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1992-03-18',
      },
      {
        id: 'preset_1_3',
        name: '王二郎',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1995-07-22',
      },
    ],
  },
  {
    label: '配偶＋父母（無子女）',
    description: '無子女時由配偶與父母共同繼承',
    decedent: {
      id: 'preset_2_decedent',
      name: '陳志明',
      deathDate: '2024-03-20',
      estateAmount: 12000000,
    },
    persons: [
      {
        id: 'preset_2_1',
        name: '林美玲',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1988-04-05',
        marriageDate: '2015-10-10',
      },
      {
        id: 'preset_2_2',
        name: '陳國華',
        relation: '父',
        status: '一般繼承',
        birthDate: '1958-01-30',
      },
      {
        id: 'preset_2_3',
        name: '張秀英',
        relation: '母',
        status: '一般繼承',
        birthDate: '1960-08-14',
      },
    ],
  },
  {
    label: '代位繼承（子女死亡由孫代位）',
    description: '子女先於被繼承人死亡，由其子女代位繼承',
    decedent: {
      id: 'preset_3_decedent',
      name: '張文雄',
      deathDate: '2024-08-10',
      estateAmount: 30000000,
    },
    persons: [
      {
        id: 'preset_3_1',
        name: '黃淑芬',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1960-12-25',
        marriageDate: '1985-06-08',
      },
      {
        id: 'preset_3_2',
        name: '張大宏',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1987-02-14',
      },
      {
        id: 'preset_3_3',
        name: '張大偉',
        relation: '子女',
        status: '死亡',
        birthDate: '1989-11-03',
        deathDate: '2024-01-05',
      },
      {
        id: 'preset_3_4',
        name: '張小明',
        relation: '子女',
        status: '代位繼承',
        birthDate: '2015-05-20',
        parentId: 'preset_3_3',
      },
      {
        id: 'preset_3_5',
        name: '張小華',
        relation: '子女',
        status: '代位繼承',
        birthDate: '2018-09-08',
        parentId: 'preset_3_3',
      },
    ],
  },
  {
    label: '再轉繼承（子女於被繼承人後死亡）',
    description: '子女於被繼承人死亡後才過世，遺產再轉由其繼承人繼承',
    decedent: {
      id: 'preset_4_decedent',
      name: '劉建國',
      deathDate: '2024-02-14',
      estateAmount: 25000000,
    },
    persons: [
      {
        id: 'preset_4_1',
        name: '周雅琪',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1968-06-30',
        marriageDate: '1993-12-18',
      },
      {
        id: 'preset_4_2',
        name: '劉家豪',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1995-04-12',
      },
      {
        id: 'preset_4_3',
        name: '劉家瑋',
        relation: '子女',
        status: '再轉繼承',
        birthDate: '1997-08-25',
        deathDate: '2024-05-20',
        marriageDate: '2020-03-15',
      },
      {
        id: 'preset_4_4',
        name: '林佳蓉',
        relation: '子女之配偶',
        status: '一般繼承',
        birthDate: '1998-01-10',
        marriageDate: '2020-03-15',
        parentId: 'preset_4_3',
      },
      {
        id: 'preset_4_5',
        name: '劉小安',
        relation: '子女',
        status: '再轉繼承',
        birthDate: '2021-11-28',
        parentId: 'preset_4_3',
      },
    ],
  },
  {
    label: '全部拋棄繼承（只剩配偶）',
    description: '所有子女拋棄繼承，僅配偶繼承全部遺產',
    decedent: {
      id: 'preset_5_decedent',
      name: '林正義',
      deathDate: '2024-09-01',
      estateAmount: 15000000,
    },
    persons: [
      {
        id: 'preset_5_1',
        name: '陳淑芳',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1970-03-15',
        marriageDate: '1995-05-20',
      },
      {
        id: 'preset_5_2',
        name: '林小明',
        relation: '子女',
        status: '拋棄繼承',
        birthDate: '1996-08-10',
      },
      {
        id: 'preset_5_3',
        name: '林小華',
        relation: '子女',
        status: '拋棄繼承',
        birthDate: '1998-12-25',
      },
    ],
  },
  {
    label: '祖父母順位（無子女、無父母）',
    description: '無子女亦無父母，由配偶與祖父母共同繼承',
    decedent: {
      id: 'preset_6_decedent',
      name: '吳明哲',
      deathDate: '2024-04-18',
      estateAmount: 8000000,
    },
    persons: [
      {
        id: 'preset_6_1',
        name: '黃雅文',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1990-07-22',
        marriageDate: '2018-11-11',
      },
      {
        id: 'preset_6_2',
        name: '吳進財',
        relation: '祖父',
        status: '一般繼承',
        birthDate: '1940-02-28',
      },
      {
        id: 'preset_6_3',
        name: '許玉蘭',
        relation: '祖母',
        status: '一般繼承',
        birthDate: '1942-06-10',
      },
    ],
  },
  {
    label: '混合代位＋再轉繼承',
    description: '同時存在代位繼承和再轉繼承的複雜情形',
    decedent: {
      id: 'preset_7_decedent',
      name: '許文龍',
      deathDate: '2024-05-15',
      estateAmount: 50000000,
    },
    persons: [
      {
        id: 'preset_7_1',
        name: '蔡美麗',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1958-11-20',
        marriageDate: '1982-09-12',
      },
      {
        id: 'preset_7_2',
        name: '許志豪',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1984-03-05',
      },
      {
        id: 'preset_7_3',
        name: '許志偉',
        relation: '子女',
        status: '死亡',
        birthDate: '1986-07-18',
        deathDate: '2023-12-01',
      },
      {
        id: 'preset_7_4',
        name: '許小龍',
        relation: '子女',
        status: '代位繼承',
        birthDate: '2012-04-22',
        parentId: 'preset_7_3',
      },
      {
        id: 'preset_7_5',
        name: '許志強',
        relation: '子女',
        status: '再轉繼承',
        birthDate: '1988-10-30',
        deathDate: '2024-07-20',
        marriageDate: '2016-06-18',
      },
      {
        id: 'preset_7_6',
        name: '王小芬',
        relation: '子女之配偶',
        status: '一般繼承',
        birthDate: '1989-02-14',
        marriageDate: '2016-06-18',
        parentId: 'preset_7_5',
      },
      {
        id: 'preset_7_7',
        name: '許小安',
        relation: '子女',
        status: '再轉繼承',
        birthDate: '2018-08-08',
        parentId: 'preset_7_5',
      },
    ],
  },
  {
    label: '兄弟姊妹順位',
    description: '無子女、無父母、無祖父母，由配偶與兄弟姊妹共同繼承',
    decedent: {
      id: 'preset_8_decedent',
      name: '蔡明宏',
      deathDate: '2024-07-30',
      estateAmount: 6000000,
    },
    persons: [
      {
        id: 'preset_8_1',
        name: '張雅婷',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1985-04-12',
        marriageDate: '2012-08-18',
      },
      {
        id: 'preset_8_2',
        name: '蔡明志',
        relation: '兄弟姊妹',
        status: '一般繼承',
        birthDate: '1980-01-25',
      },
      {
        id: 'preset_8_3',
        name: '蔡美玲',
        relation: '兄弟姊妹',
        status: '一般繼承',
        birthDate: '1988-09-15',
      },
    ],
  },
  {
    label: '多重配偶（前妻離婚＋前妻死亡＋現任）',
    description: '被繼承人歷經三段婚姻，各段婚姻皆有子女，僅現任配偶有繼承權',
    decedent: {
      id: 'preset_9_decedent',
      name: '黃國榮',
      deathDate: '2024-10-01',
      estateAmount: 24000000,
    },
    persons: [
      {
        id: 'preset_9_1',
        name: '林淑惠',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1965-03-10',
        marriageDate: '1988-05-20',
        divorceDate: '1998-08-15',
      },
      {
        id: 'preset_9_2',
        name: '陳雅芳',
        relation: '配偶',
        status: '死亡',
        birthDate: '1968-07-22',
        deathDate: '2015-11-03',
        marriageDate: '2000-02-14',
      },
      {
        id: 'preset_9_3',
        name: '張曉萍',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1975-12-08',
        marriageDate: '2018-06-30',
      },
      {
        id: 'preset_9_4',
        name: '黃志豪',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1990-01-15',
      },
      {
        id: 'preset_9_5',
        name: '黃美玲',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1995-04-28',
      },
      {
        id: 'preset_9_6',
        name: '黃俊傑',
        relation: '子女',
        status: '一般繼承',
        birthDate: '2002-09-12',
      },
      {
        id: 'preset_9_7',
        name: '黃小安',
        relation: '子女',
        status: '一般繼承',
        birthDate: '2020-03-05',
      },
    ],
  },
  {
    label: '僅配偶（無任何繼承順位者）',
    description: '被繼承人無子女、無父母、無兄弟姊妹、無祖父母，配偶獨得全部遺產',
    decedent: {
      id: 'preset_10_decedent',
      name: '趙志遠',
      deathDate: '2024-11-15',
      estateAmount: 10000000,
    },
    persons: [
      {
        id: 'preset_10_1',
        name: '孫麗華',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1980-05-20',
        marriageDate: '2010-09-18',
      },
    ],
  },
  {
    label: '無配偶、僅子女均分',
    description: '被繼承人無配偶，遺產由子女平均繼承',
    decedent: {
      id: 'preset_11_decedent',
      name: '鄭國強',
      deathDate: '2024-12-01',
      estateAmount: 20000000,
    },
    persons: [
      {
        id: 'preset_11_1',
        name: '鄭家豪',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1985-03-10',
      },
      {
        id: 'preset_11_2',
        name: '鄭家瑋',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1988-07-22',
      },
      {
        id: 'preset_11_3',
        name: '鄭美玲',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1992-01-05',
      },
    ],
  },
  {
    label: '部分拋棄繼承',
    description: '配偶與三名子女中一人拋棄繼承，由其餘繼承人分配',
    decedent: {
      id: 'preset_12_decedent',
      name: '何建民',
      deathDate: '2024-08-20',
      estateAmount: 16000000,
    },
    persons: [
      {
        id: 'preset_12_1',
        name: '方淑芬',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1972-04-15',
        marriageDate: '1998-06-20',
      },
      {
        id: 'preset_12_2',
        name: '何志明',
        relation: '子女',
        status: '一般繼承',
        birthDate: '2000-02-28',
      },
      {
        id: 'preset_12_3',
        name: '何美華',
        relation: '子女',
        status: '拋棄繼承',
        birthDate: '2002-09-12',
      },
      {
        id: 'preset_12_4',
        name: '何小安',
        relation: '子女',
        status: '一般繼承',
        birthDate: '2005-11-30',
      },
    ],
  },
  {
    label: '死亡絕嗣（子女無後代）',
    description: '子女之一死亡且無後代可代位，其份額歸其他繼承人',
    decedent: {
      id: 'preset_13_decedent',
      name: '曾文正',
      deathDate: '2024-06-10',
      estateAmount: 22000000,
    },
    persons: [
      {
        id: 'preset_13_1',
        name: '蕭雅琪',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1963-08-25',
        marriageDate: '1988-12-12',
      },
      {
        id: 'preset_13_2',
        name: '曾大偉',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1990-05-18',
      },
      {
        id: 'preset_13_3',
        name: '曾小芳',
        relation: '子女',
        status: '死亡絕嗣',
        birthDate: '1993-02-14',
        deathDate: '2023-09-01',
      },
    ],
  },
  {
    label: '三代再轉繼承（孫輩繼承）',
    description: '子女晚於被繼承人死亡，由孫子女以再轉繼承方式取得應繼分',
    decedent: {
      id: 'preset_15_decedent',
      name: '楊國輝',
      deathDate: '2024-03-10',
      estateAmount: 36000000,
    },
    persons: [
      {
        id: 'preset_15_1',
        name: '郭淑真',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1960-05-18',
        marriageDate: '1985-10-20',
      },
      {
        id: 'preset_15_2',
        name: '楊家豪',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1987-02-14',
      },
      {
        id: 'preset_15_3',
        name: '楊家偉',
        relation: '子女',
        status: '再轉繼承',
        birthDate: '1989-08-30',
        deathDate: '2024-07-15',
      },
      {
        id: 'preset_15_4',
        name: '陳雅婷',
        relation: '子女之配偶',
        status: '一般繼承',
        birthDate: '1990-11-22',
        marriageDate: '2015-06-08',
        parentId: 'preset_15_3',
      },
      {
        id: 'preset_15_5',
        name: '楊小安',
        relation: '子女',
        status: '再轉繼承',
        birthDate: '2016-04-12',
        parentId: 'preset_15_3',
      },
      {
        id: 'preset_15_6',
        name: '楊小芳',
        relation: '子女',
        status: '再轉繼承',
        birthDate: '2019-09-28',
        parentId: 'preset_15_3',
      },
    ],
  },
  {
    label: '子女配偶離婚＋再婚',
    description: '子女的前配偶已離婚，子女再婚後新配偶顯示於家族樹',
    decedent: {
      id: 'preset_16_decedent',
      name: '葉志偉',
      deathDate: '2024-11-20',
      estateAmount: 28000000,
    },
    persons: [
      {
        id: 'preset_16_1',
        name: '蘇美琪',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1962-03-15',
        marriageDate: '1987-09-10',
      },
      {
        id: 'preset_16_2',
        name: '葉大華',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1989-06-20',
      },
      {
        id: 'preset_16_3',
        name: '洪麗珠',
        relation: '子女之配偶',
        status: '一般繼承',
        birthDate: '1990-02-28',
        marriageDate: '2013-05-12',
        divorceDate: '2019-08-30',
        parentId: 'preset_16_2',
      },
      {
        id: 'preset_16_4',
        name: '方雅琳',
        relation: '子女之配偶',
        status: '一般繼承',
        birthDate: '1992-11-05',
        marriageDate: '2021-03-18',
        parentId: 'preset_16_2',
      },
      {
        id: 'preset_16_5',
        name: '葉小明',
        relation: '子女',
        status: '一般繼承',
        birthDate: '2015-01-10',
        parentId: 'preset_16_2',
      },
      {
        id: 'preset_16_6',
        name: '葉小芳',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1993-12-08',
      },
    ],
  },
  {
    label: '配偶＋僅單親（父或母一方）',
    description: '無子女，僅有配偶與母親共同繼承',
    decedent: {
      id: 'preset_14_decedent',
      name: '馬俊賢',
      deathDate: '2024-09-25',
      estateAmount: 14000000,
    },
    persons: [
      {
        id: 'preset_14_1',
        name: '葉佳玲',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1990-11-08',
        marriageDate: '2018-04-22',
      },
      {
        id: 'preset_14_2',
        name: '周秀蓮',
        relation: '母',
        status: '一般繼承',
        birthDate: '1960-06-30',
      },
    ],
  },
];
