import type { Person, Decedent } from '../types/models';

export interface Preset {
  label: string;
  description: string;
  decedent: Decedent;
  persons: Person[];
}

export const PRESETS: Preset[] = [
  {
    label: '配偶＋2名子女',
    description: '最常見的繼承情形，配偶與子女均分遺產',
    decedent: {
      id: 'preset_1_decedent',
      name: '王大明',
      deathDate: '2024-06-15',
      estateAmount: 18000000,
    },
    persons: [
      {
        id: 'preset_1_1',
        name: '李小華',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1965-09-12',
        marriageDate: '1990-11-03',
      },
      {
        id: 'preset_1_2',
        name: '王一郎',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1992-03-18',
      },
      {
        id: 'preset_1_3',
        name: '王二郎',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1995-07-22',
      },
    ],
  },
  {
    label: '配偶＋父母（無子女）',
    description: '無子女時由配偶與父母共同繼承',
    decedent: {
      id: 'preset_2_decedent',
      name: '陳志明',
      deathDate: '2024-03-20',
      estateAmount: 12000000,
    },
    persons: [
      {
        id: 'preset_2_1',
        name: '林美玲',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1988-04-05',
        marriageDate: '2015-10-10',
      },
      {
        id: 'preset_2_2',
        name: '陳國華',
        relation: '父',
        status: '一般繼承',
        birthDate: '1958-01-30',
      },
      {
        id: 'preset_2_3',
        name: '張秀英',
        relation: '母',
        status: '一般繼承',
        birthDate: '1960-08-14',
      },
    ],
  },
  {
    label: '代位繼承（子女死亡由孫代位）',
    description: '子女先於被繼承人死亡，由其子女代位繼承',
    decedent: {
      id: 'preset_3_decedent',
      name: '張文雄',
      deathDate: '2024-08-10',
      estateAmount: 30000000,
    },
    persons: [
      {
        id: 'preset_3_1',
        name: '黃淑芬',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1960-12-25',
        marriageDate: '1985-06-08',
      },
      {
        id: 'preset_3_2',
        name: '張大宏',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1987-02-14',
      },
      {
        id: 'preset_3_3',
        name: '張大偉',
        relation: '子女',
        status: '死亡',
        birthDate: '1989-11-03',
        deathDate: '2024-01-05',
      },
      {
        id: 'preset_3_4',
        name: '張小明',
        relation: '子女',
        status: '代位繼承',
        birthDate: '2015-05-20',
        parentId: 'preset_3_3',
      },
      {
        id: 'preset_3_5',
        name: '張小華',
        relation: '子女',
        status: '代位繼承',
        birthDate: '2018-09-08',
        parentId: 'preset_3_3',
      },
    ],
  },
  {
    label: '再轉繼承（子女於被繼承人後死亡）',
    description: '子女於被繼承人死亡後才過世，遺產再轉由其繼承人繼承',
    decedent: {
      id: 'preset_4_decedent',
      name: '劉建國',
      deathDate: '2024-02-14',
      estateAmount: 25000000,
    },
    persons: [
      {
        id: 'preset_4_1',
        name: '周雅琪',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1968-06-30',
        marriageDate: '1993-12-18',
      },
      {
        id: 'preset_4_2',
        name: '劉家豪',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1995-04-12',
      },
      {
        id: 'preset_4_3',
        name: '劉家瑋',
        relation: '子女',
        status: '再轉繼承',
        birthDate: '1997-08-25',
        deathDate: '2024-05-20',
        marriageDate: '2020-03-15',
      },
      {
        id: 'preset_4_4',
        name: '林佳蓉',
        relation: '子女之配偶',
        status: '再轉繼承',
        birthDate: '1998-01-10',
        marriageDate: '2020-03-15',
        parentId: 'preset_4_3',
      },
      {
        id: 'preset_4_5',
        name: '劉小安',
        relation: '子女',
        status: '再轉繼承',
        birthDate: '2021-11-28',
        parentId: 'preset_4_3',
      },
    ],
  },
  {
    label: '全部拋棄繼承（只剩配偶）',
    description: '所有子女拋棄繼承，僅配偶繼承全部遺產',
    decedent: {
      id: 'preset_5_decedent',
      name: '林正義',
      deathDate: '2024-09-01',
      estateAmount: 15000000,
    },
    persons: [
      {
        id: 'preset_5_1',
        name: '陳淑芳',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1970-03-15',
        marriageDate: '1995-05-20',
      },
      {
        id: 'preset_5_2',
        name: '林小明',
        relation: '子女',
        status: '拋棄繼承',
        birthDate: '1996-08-10',
      },
      {
        id: 'preset_5_3',
        name: '林小華',
        relation: '子女',
        status: '拋棄繼承',
        birthDate: '1998-12-25',
      },
    ],
  },
  {
    label: '祖父母順位（無子女、無父母）',
    description: '無子女亦無父母，由配偶與祖父母共同繼承',
    decedent: {
      id: 'preset_6_decedent',
      name: '吳明哲',
      deathDate: '2024-04-18',
      estateAmount: 8000000,
    },
    persons: [
      {
        id: 'preset_6_1',
        name: '黃雅文',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1990-07-22',
        marriageDate: '2018-11-11',
      },
      {
        id: 'preset_6_2',
        name: '吳進財',
        relation: '祖父',
        status: '一般繼承',
        birthDate: '1940-02-28',
      },
      {
        id: 'preset_6_3',
        name: '許玉蘭',
        relation: '祖母',
        status: '一般繼承',
        birthDate: '1942-06-10',
      },
    ],
  },
  {
    label: '混合代位＋再轉繼承',
    description: '同時存在代位繼承和再轉繼承的複雜情形',
    decedent: {
      id: 'preset_7_decedent',
      name: '許文龍',
      deathDate: '2024-05-15',
      estateAmount: 50000000,
    },
    persons: [
      {
        id: 'preset_7_1',
        name: '蔡美麗',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1958-11-20',
        marriageDate: '1982-09-12',
      },
      {
        id: 'preset_7_2',
        name: '許志豪',
        relation: '子女',
        status: '一般繼承',
        birthDate: '1984-03-05',
      },
      {
        id: 'preset_7_3',
        name: '許志偉',
        relation: '子女',
        status: '死亡',
        birthDate: '1986-07-18',
        deathDate: '2023-12-01',
      },
      {
        id: 'preset_7_4',
        name: '許小龍',
        relation: '子女',
        status: '代位繼承',
        birthDate: '2012-04-22',
        parentId: 'preset_7_3',
      },
      {
        id: 'preset_7_5',
        name: '許志強',
        relation: '子女',
        status: '再轉繼承',
        birthDate: '1988-10-30',
        deathDate: '2024-07-20',
        marriageDate: '2016-06-18',
      },
      {
        id: 'preset_7_6',
        name: '王小芬',
        relation: '子女之配偶',
        status: '再轉繼承',
        birthDate: '1989-02-14',
        marriageDate: '2016-06-18',
        parentId: 'preset_7_5',
      },
      {
        id: 'preset_7_7',
        name: '許小安',
        relation: '子女',
        status: '再轉繼承',
        birthDate: '2018-08-08',
        parentId: 'preset_7_5',
      },
    ],
  },
  {
    label: '兄弟姊妹順位',
    description: '無子女、無父母、無祖父母，由配偶與兄弟姊妹共同繼承',
    decedent: {
      id: 'preset_8_decedent',
      name: '蔡明宏',
      deathDate: '2024-07-30',
      estateAmount: 6000000,
    },
    persons: [
      {
        id: 'preset_8_1',
        name: '張雅婷',
        relation: '配偶',
        status: '一般繼承',
        birthDate: '1985-04-12',
        marriageDate: '2012-08-18',
      },
      {
        id: 'preset_8_2',
        name: '蔡明志',
        relation: '兄弟姊妹',
        status: '一般繼承',
        birthDate: '1980-01-25',
      },
      {
        id: 'preset_8_3',
        name: '蔡美玲',
        relation: '兄弟姊妹',
        status: '一般繼承',
        birthDate: '1988-09-15',
      },
    ],
  },
];
